before_install:
  - wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
  - echo "[extensions]" > $HOME/.hgrc
  - echo "hgext.mq =" >> $HOME/.hgrc
language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2
script: mvn install -B -q
